import type { Show, Episode } from "./supabase/types";

export const SHOWS: Show[] = [
  {
    id: "show-1",
    title: "Neon Horizon",
    description:
      "In een cyberpunk megastad jaagt detective Mara Vale op een seriemoordenaar die digitale vingerafdrukken achterlaat in het neurale netwerk van de stad. Een gripping noir-thriller set in 2087.",
    thumbnail: "https://picsum.photos/seed/neon1/400/600",
    banner: "https://picsum.photos/seed/neonbanner1/1920/800",
    category: "series",
    genres: ["Thriller", "Sci-Fi", "Crime"],
    year: 2024,
    rating: "TV-MA",
    featured: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "show-2",
    title: "The Last Harvest",
    description:
      "Een boerenfamilie vecht om hun land te redden van een groot agro-concern, terwijl ze een duister geheim ontdekken dat begraven ligt onder hun akkers.",
    thumbnail: "https://picsum.photos/seed/harvest2/400/600",
    banner: "https://picsum.photos/seed/harvestbanner2/1920/800",
    category: "series",
    genres: ["Drama", "Mystery"],
    year: 2023,
    rating: "TV-14",
    featured: false,
    created_at: "2024-01-02T00:00:00Z",
  },
  {
    id: "show-3",
    title: "Velocity",
    description:
      "De meest gewaagde straatrenner ter wereld moet illegale circuits over vijf continenten doorkruisen om de naam van zijn broer te zuiveren.",
    thumbnail: "https://picsum.photos/seed/velocity3/400/600",
    banner: "https://picsum.photos/seed/velocitybanner3/1920/800",
    category: "movie",
    genres: ["Actie", "Thriller"],
    year: 2024,
    rating: "PG-13",
    featured: false,
    created_at: "2024-01-03T00:00:00Z",
  },
  {
    id: "show-4",
    title: "Deep Blue Silence",
    description:
      "Een mariene bioloog ontdekt een oude intelligentie in de Marianentrog. Maar contact maken kan haar alles kosten.",
    thumbnail: "https://picsum.photos/seed/ocean4/400/600",
    banner: "https://picsum.photos/seed/oceanbanner4/1920/800",
    category: "movie",
    genres: ["Sci-Fi", "Avontuur"],
    year: 2023,
    rating: "PG-13",
    featured: false,
    created_at: "2024-01-04T00:00:00Z",
  },
  {
    id: "show-5",
    title: "Crowned",
    description:
      "Achter de glinsterende façade van Europa's laatste absolute monarchie breken loyaliteiten en brokkelen allianties af terwijl de gezondheid van de koning achteruitgaat.",
    thumbnail: "https://picsum.photos/seed/crown5/400/600",
    banner: "https://picsum.photos/seed/crownbanner5/1920/800",
    category: "series",
    genres: ["Drama", "Historisch"],
    year: 2024,
    rating: "TV-14",
    featured: false,
    created_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "show-6",
    title: "Laughing Stock",
    description:
      "Een stand-upcomedian wordt ingehuurd als persoonlijke coach van een CEO en redt per ongeluk het bedrijf.",
    thumbnail: "https://picsum.photos/seed/comedy6/400/600",
    banner: "https://picsum.photos/seed/comedybanner6/1920/800",
    category: "series",
    genres: ["Komedie"],
    year: 2024,
    rating: "TV-14",
    featured: false,
    created_at: "2024-01-06T00:00:00Z",
  },
  {
    id: "show-7",
    title: "Iron Verdict",
    description:
      "Een onverbiddelijke rechter navigeert door een rechtssysteem dat tot op het bot verrot is en vecht geval per geval tegen corruptie.",
    thumbnail: "https://picsum.photos/seed/judge7/400/600",
    banner: "https://picsum.photos/seed/judgebanner7/1920/800",
    category: "series",
    genres: ["Crime", "Drama"],
    year: 2023,
    rating: "TV-MA",
    featured: false,
    created_at: "2024-01-07T00:00:00Z",
  },
  {
    id: "show-8",
    title: "Frostbound",
    description:
      "Een overlevingsverhaal in de Arctis: zes vreemdelingen gestrand na een vliegtuigcrash moeten samenwerken — of sterven.",
    thumbnail: "https://picsum.photos/seed/frost8/400/600",
    banner: "https://picsum.photos/seed/frostbanner8/1920/800",
    category: "series",
    genres: ["Thriller", "Avontuur"],
    year: 2024,
    rating: "TV-14",
    featured: false,
    created_at: "2024-01-08T00:00:00Z",
  },
  {
    id: "show-9",
    title: "Wavelength",
    description:
      "Twee vreemdelingen beginnen elkaars gedachten te horen via een onverklaarbare verbinding — en worden gevaarlijk verliefd.",
    thumbnail: "https://picsum.photos/seed/wave9/400/600",
    banner: "https://picsum.photos/seed/wavebanner9/1920/800",
    category: "movie",
    genres: ["Romantiek", "Sci-Fi"],
    year: 2023,
    rating: "PG-13",
    featured: false,
    created_at: "2024-01-09T00:00:00Z",
  },
  {
    id: "show-10",
    title: "The Botanist",
    description:
      "Een teruggetrokken plantenonderzoeker maakt per ongeluk een bewust organisme aan en moet het lot ervan bepalen voordat de overheid het ontdekt.",
    thumbnail: "https://picsum.photos/seed/plant10/400/600",
    banner: "https://picsum.photos/seed/plantbanner10/1920/800",
    category: "movie",
    genres: ["Sci-Fi", "Drama"],
    year: 2024,
    rating: "PG-13",
    featured: false,
    created_at: "2024-01-10T00:00:00Z",
  },
];

export const EPISODES: Episode[] = [
  // Neon Horizon S1
  {
    id: "ep-1-1",
    show_id: "show-1",
    title: "Ghost Signal",
    description: "Detective Mara Vale ontvangt een cryptische tip van een anonieme bron binnen het neurale raster.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    season: 1, episode_number: 1, duration: 2640,
    thumbnail: "https://picsum.photos/seed/ep11/400/225",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "ep-1-2",
    show_id: "show-1",
    title: "Phantom Protocol",
    description: "De moordenaar slaat opnieuw toe en laat een spoor achter dat alleen Mara kan ontcijferen.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    season: 1, episode_number: 2, duration: 2820,
    thumbnail: "https://picsum.photos/seed/ep12/400/225",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "ep-1-3",
    show_id: "show-1",
    title: "Layers",
    description: "Mara gaat undercover in de illegale augmentatiemarkt van de stad.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    season: 1, episode_number: 3, duration: 2700,
    thumbnail: "https://picsum.photos/seed/ep13/400/225",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "ep-1-4",
    show_id: "show-1",
    title: "Dead Frequency",
    description: "Een getuige verdwijnt net voordat hij zou getuigen.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    season: 1, episode_number: 4, duration: 2760,
    thumbnail: "https://picsum.photos/seed/ep14/400/225",
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "ep-1-5",
    show_id: "show-1",
    title: "Dark Matter",
    description: "Het spoor leidt Mara naar de hoogste niveaus van de bedrijfsmacht.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    season: 1, episode_number: 5, duration: 3180,
    thumbnail: "https://picsum.photos/seed/ep15/400/225",
    created_at: "2024-01-01T00:00:00Z",
  },
  // The Last Harvest S1
  {
    id: "ep-2-1",
    show_id: "show-2",
    title: "Roots",
    description: "De familie Calloway bereidt zich voor op een moeilijk seizoen op hun voorouderlijke boerderij.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    season: 1, episode_number: 1, duration: 2580,
    thumbnail: "https://picsum.photos/seed/ep21/400/225",
    created_at: "2024-01-02T00:00:00Z",
  },
  {
    id: "ep-2-2",
    show_id: "show-2",
    title: "The Offer",
    description: "Een verdacht overnamebod van MegaCrop Inc. arriveert.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    season: 1, episode_number: 2, duration: 2520,
    thumbnail: "https://picsum.photos/seed/ep22/400/225",
    created_at: "2024-01-02T00:00:00Z",
  },
  {
    id: "ep-2-3",
    show_id: "show-2",
    title: "What Lies Beneath",
    description: "Graafwerkzaamheden op het verre veld onthullen iets dat nooit gevonden had mogen worden.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    season: 1, episode_number: 3, duration: 2700,
    thumbnail: "https://picsum.photos/seed/ep23/400/225",
    created_at: "2024-01-02T00:00:00Z",
  },
  // Velocity (movie)
  {
    id: "ep-3-1",
    show_id: "show-3",
    title: "Velocity",
    description: "Volledige film — illegaal racen over vijf continenten.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    season: 1, episode_number: 1, duration: 6840,
    thumbnail: "https://picsum.photos/seed/ep31/400/225",
    created_at: "2024-01-03T00:00:00Z",
  },
  // Deep Blue Silence (movie)
  {
    id: "ep-4-1",
    show_id: "show-4",
    title: "Deep Blue Silence",
    description: "Volledige film — de Marianentrog verbergt meer dan vis.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    season: 1, episode_number: 1, duration: 7200,
    thumbnail: "https://picsum.photos/seed/ep41/400/225",
    created_at: "2024-01-04T00:00:00Z",
  },
  // Crowned S1
  {
    id: "ep-5-1",
    show_id: "show-5",
    title: "The Throne Room",
    description: "De toestand van de koning verslechtert, wat een strijd om de troonopvolging ontketent.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    season: 1, episode_number: 1, duration: 3000,
    thumbnail: "https://picsum.photos/seed/ep51/400/225",
    created_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "ep-5-2",
    show_id: "show-5",
    title: "Alliances",
    description: "De koninklijke raad smeedt onwaarschijnlijke samenwerkingen.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    season: 1, episode_number: 2, duration: 2880,
    thumbnail: "https://picsum.photos/seed/ep52/400/225",
    created_at: "2024-01-05T00:00:00Z",
  },
  // Laughing Stock S1
  {
    id: "ep-6-1",
    show_id: "show-6",
    title: "Day One",
    description: "De eerste dag van Marcus als CEO-coach loopt spectaculair fout.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    season: 1, episode_number: 1, duration: 1740,
    thumbnail: "https://picsum.photos/seed/ep61/400/225",
    created_at: "2024-01-06T00:00:00Z",
  },
  {
    id: "ep-6-2",
    show_id: "show-6",
    title: "The Pitch",
    description: "Marcus wordt per ongeluk voor de raad van bestuur gezet.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    season: 1, episode_number: 2, duration: 1800,
    thumbnail: "https://picsum.photos/seed/ep62/400/225",
    created_at: "2024-01-06T00:00:00Z",
  },
  // Iron Verdict S1
  {
    id: "ep-7-1",
    show_id: "show-7",
    title: "Eerste Zitting",
    description: "Rechter Torres neemt een zaak aan die niemand anders durft aan te nemen.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    season: 1, episode_number: 1, duration: 2640,
    thumbnail: "https://picsum.photos/seed/ep71/400/225",
    created_at: "2024-01-07T00:00:00Z",
  },
  // Frostbound S1
  {
    id: "ep-8-1",
    show_id: "show-8",
    title: "Crash Landing",
    description: "Zes overlevenden realiseren zich dat redding misschien nooit komt.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    season: 1, episode_number: 1, duration: 2700,
    thumbnail: "https://picsum.photos/seed/ep81/400/225",
    created_at: "2024-01-08T00:00:00Z",
  },
  // Wavelength (movie)
  {
    id: "ep-9-1",
    show_id: "show-9",
    title: "Wavelength",
    description: "Volledige film — twee zielen, één frequentie.",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    season: 1, episode_number: 1, duration: 6300,
    thumbnail: "https://picsum.photos/seed/ep91/400/225",
    created_at: "2024-01-09T00:00:00Z",
  },
  // The Botanist (movie)
  {
    id: "ep-10-1",
    show_id: "show-10",
    title: "The Botanist",
    description: "Volledige film — wat als planten konden denken?",
    video_url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    season: 1, episode_number: 1, duration: 6600,
    thumbnail: "https://picsum.photos/seed/ep101/400/225",
    created_at: "2024-01-10T00:00:00Z",
  },
];
