import type { Show, Episode } from "./supabase/types";

// Real VTM GO thumbnail & banner URLs scraped from vtmgo.be (persgroep CDN)
const IMAGES: Record<string, { thumb: string; banner: string }> = {
  "the-voice": {
    thumb: "https://images4.persgroep.net/rcs/HUiNzd50PDpbiH73pino_dVQJsg/diocontent/268968071/_fitwidth/426",
    banner: "https://images4.persgroep.net/rcs/HUiNzd50PDpbiH73pino_dVQJsg/diocontent/268968071/_fitwidth/1400",
  },
  "boho": {
    thumb: "https://images3.persgroep.net/rcs/Fdc1LAyocmQryhSqPCAPP_Vt4Yk/diocontent/269872633/_fitwidth/426",
    banner: "https://images3.persgroep.net/rcs/Fdc1LAyocmQryhSqPCAPP_Vt4Yk/diocontent/269872633/_fitwidth/1400",
  },
  "expeditie-gooris": {
    thumb: "https://images3.persgroep.net/rcs/Vbf1Fb41JWCQl5VkRVRFltb8CwU/diocontent/269090368/_fitwidth/426",
    banner: "https://images3.persgroep.net/rcs/Vbf1Fb41JWCQl5VkRVRFltb8CwU/diocontent/269090368/_fitwidth/1400",
  },
  "zoo": {
    thumb: "https://images4.persgroep.net/rcs/IOnhFVwnOQhpFxaM0HfycqmpnW0/diocontent/269256948/_fitwidth/426",
    banner: "https://images4.persgroep.net/rcs/IOnhFVwnOQhpFxaM0HfycqmpnW0/diocontent/269256948/_fitwidth/1400",
  },
  "moordzaken": {
    thumb: "https://images4.persgroep.net/rcs/Ft7x7ppm4nMRudbZIKj83inL6H8/diocontent/261558844/_fitwidth/426",
    banner: "https://images4.persgroep.net/rcs/Ft7x7ppm4nMRudbZIKj83inL6H8/diocontent/261558844/_fitwidth/1400",
  },
  "de-box": {
    thumb: "https://images0.persgroep.net/rcs/yta9efEOE_erfJppKvXKzqAI3uw/diocontent/269078029/_fitwidth/426",
    banner: "https://images0.persgroep.net/rcs/yta9efEOE_erfJppKvXKzqAI3uw/diocontent/269078029/_fitwidth/1400",
  },
  "datenight": {
    thumb: "https://images2.persgroep.net/rcs/NSd_UySbDxK-eHmhZLo7oGQiuRo/diocontent/270675842/_fitwidth/426",
    banner: "https://images2.persgroep.net/rcs/NSd_UySbDxK-eHmhZLo7oGQiuRo/diocontent/270675842/_fitwidth/1400",
  },
  "de-muttis": {
    thumb: "https://images2.persgroep.net/rcs/YzFt5YmRwJpp-2C1MFLvZzzjMmg/diocontent/268103919/_fitwidth/426",
    banner: "https://images2.persgroep.net/rcs/YzFt5YmRwJpp-2C1MFLvZzzjMmg/diocontent/268103919/_fitwidth/1400",
  },
  "gooische-vrouwen": {
    thumb: "https://images2.persgroep.net/rcs/zpwMtKj57FCFFBMmZ8Za6XIO17s/diocontent/268837097/_fitwidth/426",
    banner: "https://images2.persgroep.net/rcs/zpwMtKj57FCFFBMmZ8Za6XIO17s/diocontent/268837097/_fitwidth/1400",
  },
  "familie": {
    thumb: "https://images2.persgroep.net/rcs/_FbT7hoDekSrSXV6nnNwqvD9Sq4/diocontent/268388758/_fitwidth/426",
    banner: "https://images2.persgroep.net/rcs/_FbT7hoDekSrSXV6nnNwqvD9Sq4/diocontent/268388758/_fitwidth/1400",
  },
  "alter-ego": {
    thumb: "https://images1.persgroep.net/rcs/i-Nz_ic--VO7AckG28NutegRNOo/diocontent/237603247/_fitwidth/426",
    banner: "https://images1.persgroep.net/rcs/i-Nz_ic--VO7AckG28NutegRNOo/diocontent/237603247/_fitwidth/1400",
  },
  "verliefd": {
    thumb: "https://images0.persgroep.net/rcs/YRZkTXhbp7LqhGdwUBZehodrHpk/diocontent/247674621/_fitwidth/426",
    banner: "https://images0.persgroep.net/rcs/YRZkTXhbp7LqhGdwUBZehodrHpk/diocontent/247674621/_fitwidth/1400",
  },
  "tracker": {
    thumb: "https://images2.persgroep.net/rcs/UDxM5Sy4F-YAR0E6DT0J0filz1c/diocontent/268673979/_fitwidth/426",
    banner: "https://images2.persgroep.net/rcs/UDxM5Sy4F-YAR0E6DT0J0filz1c/diocontent/268673979/_fitwidth/1400",
  },
  "couple-next-door": {
    thumb: "https://images4.persgroep.net/rcs/9O_lcbmWMPe-8PS5vdR-msI6rgc/diocontent/269817420/_fitwidth/426",
    banner: "https://images4.persgroep.net/rcs/9O_lcbmWMPe-8PS5vdR-msI6rgc/diocontent/269817420/_fitwidth/1400",
  },
  "love-island": {
    thumb: "https://images2.persgroep.net/rcs/MOye-p7c6DTyzEzUDD4RyS1OLkM/diocontent/270120589/_fitwidth/426",
    banner: "https://images2.persgroep.net/rcs/MOye-p7c6DTyzEzUDD4RyS1OLkM/diocontent/270120589/_fitwidth/1400",
  },
  "florentina": {
    thumb: "https://images1.persgroep.net/rcs/JWJiZz6St-kO6rMPMTxBfphxb_w/diocontent/266619074/_fitwidth/426",
    banner: "https://images1.persgroep.net/rcs/JWJiZz6St-kO6rMPMTxBfphxb_w/diocontent/266619074/_fitwidth/1400",
  },
  "huis-gemaakt": {
    thumb: "https://images0.persgroep.net/rcs/YPN_1rTzxwtNNQt3ZGmI7tYVN24/diocontent/270039178/_fitwidth/426",
    banner: "https://images0.persgroep.net/rcs/YPN_1rTzxwtNNQt3ZGmI7tYVN24/diocontent/270039178/_fitwidth/1400",
  },
  "hamnet": {
    thumb: "https://images3.persgroep.net/rcs/lJG0FJis9TK_hRUw7TBpkxl6Ed0/diocontent/270374156/_fitwidth/426",
    banner: "https://images3.persgroep.net/rcs/lJG0FJis9TK_hRUw7TBpkxl6Ed0/diocontent/270374156/_fitwidth/1400",
  },
  "spider-man": {
    thumb: "https://images0.persgroep.net/rcs/zlcC7f_XEnTmx_9hkDjXP9C6DI0/diocontent/259358566/_fitwidth/426",
    banner: "https://images0.persgroep.net/rcs/zlcC7f_XEnTmx_9hkDjXP9C6DI0/diocontent/259358566/_fitwidth/1400",
  },
  "spider-man-2": {
    thumb: "https://images4.persgroep.net/rcs/M1YHOBk3VTYhcxzCpOQoalEC3xo/diocontent/252790014/_fitwidth/426",
    banner: "https://images4.persgroep.net/rcs/M1YHOBk3VTYhcxzCpOQoalEC3xo/diocontent/252790014/_fitwidth/1400",
  },
  "spider-man-3": {
    thumb: "https://images1.persgroep.net/rcs/wq9ytAd0VrW34qNsKh49dqszHf0/diocontent/247128052/_fitwidth/426",
    banner: "https://images1.persgroep.net/rcs/wq9ytAd0VrW34qNsKh49dqszHf0/diocontent/247128052/_fitwidth/1400",
  },
  "king-of-thieves": {
    thumb: "https://images4.persgroep.net/rcs/WPHcqm8vzSnpdApE88bwAyFGXt4/diocontent/253162122/_fitwidth/426",
    banner: "https://images4.persgroep.net/rcs/WPHcqm8vzSnpdApE88bwAyFGXt4/diocontent/253162122/_fitwidth/1400",
  },
  "swordfish": {
    thumb: "https://images4.persgroep.net/rcs/3v-nPo83vBI7y571hllRXVcXdKg/diocontent/247795775/_fitwidth/426",
    banner: "https://images4.persgroep.net/rcs/3v-nPo83vBI7y571hllRXVcXdKg/diocontent/247795775/_fitwidth/1400",
  },
  "lock-out": {
    thumb: "https://images3.persgroep.net/rcs/LnUmP-SJBJjkPBXeuU6xYn--MRQ/diocontent/263688487/_fitwidth/426",
    banner: "https://images3.persgroep.net/rcs/LnUmP-SJBJjkPBXeuU6xYn--MRQ/diocontent/263688487/_fitwidth/1400",
  },
};

// Sample video URLs — swap for real streams when available
const VIDEOS = [
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
];

export const SHOWS: Show[] = [
  // ── SERIES ────────────────────────────────────────────────────────────────
  {
    id: "show-1",
    title: "The Voice van Vlaanderen",
    description: "Een muzikale talentenjacht waarin vier bekende coaches op zoek gaan naar dé stem van Vlaanderen.",
    thumbnail: IMAGES["the-voice"].thumb,
    banner: IMAGES["the-voice"].banner,
    category: "series",
    genres: ["Reality", "Muziek", "Entertainment"],
    year: 2025,
    rating: "AL",
    featured: true,
    created_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "show-2",
    title: "BOHO",
    description: "Kima verliest haar job en stort zich op een zot idee. Nawal worstelt met haar kinderwens. Alex vindt dat Flamands het wel heel makkelijk hebben. Drie vriendinnen uit Borgerhout zoeken naar geluk.",
    thumbnail: IMAGES["boho"].thumb,
    banner: IMAGES["boho"].banner,
    category: "series",
    genres: ["Drama", "Komedie"],
    year: 2025,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-02T00:00:00Z",
  },
  {
    id: "show-3",
    title: "Expeditie Gooris",
    description: "In Expeditie Gooris trekt het sympathiekste gezin van Vlaanderen samen de wereld in. Sam Gooris, echtgenote Kelly, dochter Shania en zoon Kenji gaan samen op roadtrip.",
    thumbnail: IMAGES["expeditie-gooris"].thumb,
    banner: IMAGES["expeditie-gooris"].banner,
    category: "series",
    genres: ["Reality", "Avontuur", "Familie"],
    year: 2025,
    rating: "AL",
    featured: false,
    created_at: "2025-01-03T00:00:00Z",
  },
  {
    id: "show-4",
    title: "Het Echte Leven in de ZOO",
    description: "Ontdek het leven in de allereerste dierentuin van ons land: ZOO Planckendael. Niet zoals een gewone wildlifereportagereeks, maar wel bekeken en verteld vanuit het standpunt van de dieren zelf.",
    thumbnail: IMAGES["zoo"].thumb,
    banner: IMAGES["zoo"].banner,
    category: "series",
    genres: ["Documentaire", "Natuur", "Familie"],
    year: 2025,
    rating: "AL",
    featured: false,
    created_at: "2025-01-04T00:00:00Z",
  },
  {
    id: "show-5",
    title: "Moordzaken: Liefde is geen Alibi",
    description: "Wanneer liefde, jaloezie en haat een gruwelijke cocktail vormen, slaan de stoppen door. Reconstructies van moordzaken in de relationele sfeer.",
    thumbnail: IMAGES["moordzaken"].thumb,
    banner: IMAGES["moordzaken"].banner,
    category: "series",
    genres: ["Crime", "Thriller", "Documentaire"],
    year: 2025,
    rating: "TV-MA",
    featured: false,
    created_at: "2025-01-05T00:00:00Z",
  },
  {
    id: "show-6",
    title: "De Box",
    description: "Tien onbekende Vlamingen starten aan een spel waarvan ze de regels niet kennen. Na het openen van een box start de opdracht meteen, zonder extra uitleg.",
    thumbnail: IMAGES["de-box"].thumb,
    banner: IMAGES["de-box"].banner,
    category: "series",
    genres: ["Reality", "Spel"],
    year: 2025,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-06T00:00:00Z",
  },
  {
    id: "show-7",
    title: "Datenight",
    description: "Tess Goossens duikt met verschillende BV's de wereld van de liefde in. We komen meer te weten over hun eerste liefde, de impact van liefdesverdriet en hun stoutste slaapkamergeheimen.",
    thumbnail: IMAGES["datenight"].thumb,
    banner: IMAGES["datenight"].banner,
    category: "series",
    genres: ["Entertainment", "Romantiek", "Komedie"],
    year: 2025,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-07T00:00:00Z",
  },
  {
    id: "show-8",
    title: "De Mutti's",
    description: "Zeven bekende mama's starten met de praatgroep die alle mama's nodig hebben. Ze delen hun frustraties in een herkenbare, luchtige babbel vol humor en inzichten.",
    thumbnail: IMAGES["de-muttis"].thumb,
    banner: IMAGES["de-muttis"].banner,
    category: "series",
    genres: ["Komedie", "Entertainment", "Reality"],
    year: 2025,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-08T00:00:00Z",
  },
  {
    id: "show-9",
    title: "Gooische Vrouwen",
    description: "Ze hebben geld in overvloed, rijden in luxueuze auto's en wonen in enorme huizen. Maar enkele vriendinnen uit het Gooi ontdekken al snel dat goud niet altijd blinkt.",
    thumbnail: IMAGES["gooische-vrouwen"].thumb,
    banner: IMAGES["gooische-vrouwen"].banner,
    category: "series",
    genres: ["Drama", "Komedie"],
    year: 2024,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-09T00:00:00Z",
  },
  {
    id: "show-10",
    title: "Familie",
    description: "Vlaamse dagelijkse serie over het wel en wee van de familie Van den Bossche en hun entourage.",
    thumbnail: IMAGES["familie"].thumb,
    banner: IMAGES["familie"].banner,
    category: "series",
    genres: ["Drama", "Soap", "Familie"],
    year: 2025,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-10T00:00:00Z",
  },
  {
    id: "show-11",
    title: "Alter Ego",
    description: "Jaren na het tragische verlies van zijn jeugdliefde duikt een mysterieus figuur opnieuw op. Gilles zijn zoektocht leidt hem naar de private bank Salvator, waar een verborgen wereld schuilgaat.",
    thumbnail: IMAGES["alter-ego"].thumb,
    banner: IMAGES["alter-ego"].banner,
    category: "series",
    genres: ["Thriller", "Drama", "Mystery"],
    year: 2024,
    rating: "TV-MA",
    featured: false,
    created_at: "2025-01-11T00:00:00Z",
  },
  {
    id: "show-12",
    title: "Verliefd, verloofd, getrouwd in 24u",
    description: "Verliefd, verloofd, getrouwd: de meeste koppels doen er weken of jaren over, maar de koppels in dit avontuur beleven hun droomdag binnen de 24 uur na het aanzoek.",
    thumbnail: IMAGES["verliefd"].thumb,
    banner: IMAGES["verliefd"].banner,
    category: "series",
    genres: ["Reality", "Romantiek"],
    year: 2024,
    rating: "AL",
    featured: false,
    created_at: "2025-01-12T00:00:00Z",
  },
  {
    id: "show-13",
    title: "Tracker",
    description: "Voormalig sluipschutter Colter Shaw gebruikt zijn deskundige speurvaardigheden om vermiste personen op te sporen in ruil voor een fikse vergoeding.",
    thumbnail: IMAGES["tracker"].thumb,
    banner: IMAGES["tracker"].banner,
    category: "series",
    genres: ["Actie", "Drama", "Thriller"],
    year: 2025,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-13T00:00:00Z",
  },
  {
    id: "show-14",
    title: "The Couple Next Door",
    description: "De zwangere Evie en haar partner verhuizen naar een chique Engelse buitenwijk. Daar ontstaat een intense vriendschap met hun buren en de spanning tussen de vier is vanaf de eerste ontmoeting te snijden.",
    thumbnail: IMAGES["couple-next-door"].thumb,
    banner: IMAGES["couple-next-door"].banner,
    category: "series",
    genres: ["Drama", "Thriller", "Romantiek"],
    year: 2025,
    rating: "TV-MA",
    featured: false,
    created_at: "2025-01-14T00:00:00Z",
  },
  {
    id: "show-15",
    title: "Love Island UK",
    description: "Britse realityshow waarin sexy, jonge singles op zoek gaan naar de liefde tijdens hun verblijf in een luxe villa op een prachtige locatie.",
    thumbnail: IMAGES["love-island"].thumb,
    banner: IMAGES["love-island"].banner,
    category: "series",
    genres: ["Reality", "Romantiek", "Entertainment"],
    year: 2025,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-15T00:00:00Z",
  },
  {
    id: "show-16",
    title: "Florentina",
    description: "Flo is een spontane, charmante flapuit die haar mannetje staat in het harde gezondheids- en fitnessbedrijf van haar moeder. Net voor haar huwelijk wordt ze gedumpt en erft ze een geheime nachtclub.",
    thumbnail: IMAGES["florentina"].thumb,
    banner: IMAGES["florentina"].banner,
    category: "series",
    genres: ["Komedie", "Drama", "Romantiek"],
    year: 2025,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-16T00:00:00Z",
  },
  {
    id: "show-17",
    title: "Huis Gemaakt",
    description: "Onder het motto 'verbouw een huis en win een thuis' halen gedreven koppels hun beste renovatieskills naar boven om de ultieme droomprijs te winnen: een eigen huis, gratis en voor niks.",
    thumbnail: IMAGES["huis-gemaakt"].thumb,
    banner: IMAGES["huis-gemaakt"].banner,
    category: "series",
    genres: ["Reality", "Lifestyle"],
    year: 2025,
    rating: "AL",
    featured: false,
    created_at: "2025-01-17T00:00:00Z",
  },

  // ── FILMS ─────────────────────────────────────────────────────────────────
  {
    id: "show-18",
    title: "Hamnet",
    description: "Het meeslepende verhaal van liefde en verlies dat de inspiratie vormde voor een van Shakespeares bekendste werken: Hamlet.",
    thumbnail: IMAGES["hamnet"].thumb,
    banner: IMAGES["hamnet"].banner,
    category: "movie",
    genres: ["Drama", "Historisch", "Romantiek"],
    year: 2025,
    rating: "TV-14",
    featured: false,
    created_at: "2025-01-18T00:00:00Z",
  },
  {
    id: "show-19",
    title: "Spider-Man",
    description: "Wanneer student Peter Parker gebeten wordt door een radioactieve spin, krijgt hij superkrachten. Na de moord op zijn oom besluit hij de misdaad te bestrijden als Spider-Man.",
    thumbnail: IMAGES["spider-man"].thumb,
    banner: IMAGES["spider-man"].banner,
    category: "movie",
    genres: ["Actie", "Avontuur", "Sci-Fi"],
    year: 2002,
    rating: "PG-13",
    featured: false,
    created_at: "2025-01-19T00:00:00Z",
  },
  {
    id: "show-20",
    title: "Spider-Man 2",
    description: "Peter Parker worstelt met zijn leven als student en superheld. Net als hij wil opgeven, veroorzaakt dokter Octavius ravage en ontvoert Mary Jane.",
    thumbnail: IMAGES["spider-man-2"].thumb,
    banner: IMAGES["spider-man-2"].banner,
    category: "movie",
    genres: ["Actie", "Avontuur", "Sci-Fi"],
    year: 2004,
    rating: "PG-13",
    featured: false,
    created_at: "2025-01-20T00:00:00Z",
  },
  {
    id: "show-21",
    title: "Spider-Man 3",
    description: "Peter Parker en MJ willen trouwen. Na een avond in het park wordt Peter besmet door een meteoriet en transformeert hij in iets duisters.",
    thumbnail: IMAGES["spider-man-3"].thumb,
    banner: IMAGES["spider-man-3"].banner,
    category: "movie",
    genres: ["Actie", "Avontuur", "Sci-Fi"],
    year: 2007,
    rating: "PG-13",
    featured: false,
    created_at: "2025-01-21T00:00:00Z",
  },
  {
    id: "show-22",
    title: "King of Thieves",
    description: "Na de dood van zijn vrouw komt de bejaarde meesterdief Brian Reader uit pensioen voor een laatste kraak. Samen met een bende criminelen steelt hij miljoenen aan juwelen in Hatton Garden.",
    thumbnail: IMAGES["king-of-thieves"].thumb,
    banner: IMAGES["king-of-thieves"].banner,
    category: "movie",
    genres: ["Crime", "Drama", "Thriller"],
    year: 2018,
    rating: "TV-MA",
    featured: false,
    created_at: "2025-01-22T00:00:00Z",
  },
  {
    id: "show-23",
    title: "Swordfish",
    description: "Stanley Jobson, een gewiekste hacker, wordt vrijgelaten uit de gevangenis op voorwaarde dat hij geen computer meer aanraakt. Een voorstel dat hij moeilijk kan afslaan, brengt hem in gevaar.",
    thumbnail: IMAGES["swordfish"].thumb,
    banner: IMAGES["swordfish"].banner,
    category: "movie",
    genres: ["Actie", "Thriller", "Crime"],
    year: 2001,
    rating: "TV-MA",
    featured: false,
    created_at: "2025-01-23T00:00:00Z",
  },
  {
    id: "show-24",
    title: "Lock Out",
    description: "2079: MS One is een experimentele gevangenis in de ruimte. Wanneer de dochter van de president gegijzeld wordt, stuurt hij agent Snow op reddingsmissie.",
    thumbnail: IMAGES["lock-out"].thumb,
    banner: IMAGES["lock-out"].banner,
    category: "movie",
    genres: ["Actie", "Sci-Fi", "Thriller"],
    year: 2012,
    rating: "PG-13",
    featured: false,
    created_at: "2025-01-24T00:00:00Z",
  },
];

export const EPISODES: Episode[] = [
  // The Voice van Vlaanderen S1
  { id: "ep-1-1", show_id: "show-1", title: "De Blind Auditions (1)", description: "De coaches draaien hun stoel voor de beste stemmen van Vlaanderen.", video_url: VIDEOS[0], season: 1, episode_number: 1, duration: 5400, thumbnail: IMAGES["the-voice"].thumb, created_at: "2025-01-01T00:00:00Z" },
  { id: "ep-1-2", show_id: "show-1", title: "De Blind Auditions (2)", description: "Meer verrassende talenten doen hun best om de coaches te overtuigen.", video_url: VIDEOS[1], season: 1, episode_number: 2, duration: 5400, thumbnail: IMAGES["the-voice"].thumb, created_at: "2025-01-01T00:00:00Z" },
  { id: "ep-1-3", show_id: "show-1", title: "De Battle Rounds", description: "Twee talenten, één coach en één plek in het team.", video_url: VIDEOS[2], season: 1, episode_number: 3, duration: 5400, thumbnail: IMAGES["the-voice"].thumb, created_at: "2025-01-01T00:00:00Z" },

  // BOHO S1
  { id: "ep-2-1", show_id: "show-2", title: "Pilot", description: "Kima, Nawal en Alex starten een onverwacht avontuur in Borgerhout.", video_url: VIDEOS[3], season: 1, episode_number: 1, duration: 2700, thumbnail: IMAGES["boho"].thumb, created_at: "2025-01-02T00:00:00Z" },
  { id: "ep-2-2", show_id: "show-2", title: "Het Plan", description: "Het wilde idee van Kima begint vorm te krijgen.", video_url: VIDEOS[4], season: 1, episode_number: 2, duration: 2700, thumbnail: IMAGES["boho"].thumb, created_at: "2025-01-02T00:00:00Z" },
  { id: "ep-2-3", show_id: "show-2", title: "Tegenslagen", description: "Nawal krijgt slecht nieuws en de vriendinnen staan voor een keuzemoment.", video_url: VIDEOS[5], season: 1, episode_number: 3, duration: 2700, thumbnail: IMAGES["boho"].thumb, created_at: "2025-01-02T00:00:00Z" },

  // Expeditie Gooris S1
  { id: "ep-3-1", show_id: "show-3", title: "Vertrek naar het onbekende", description: "Het gezin Gooris vertrekt naar hun eerste bestemming.", video_url: VIDEOS[6], season: 1, episode_number: 1, duration: 3600, thumbnail: IMAGES["expeditie-gooris"].thumb, created_at: "2025-01-03T00:00:00Z" },
  { id: "ep-3-2", show_id: "show-3", title: "Avontuur in de jungle", description: "Sam en Kelly worden op de proef gesteld door de natuur.", video_url: VIDEOS[7], season: 1, episode_number: 2, duration: 3600, thumbnail: IMAGES["expeditie-gooris"].thumb, created_at: "2025-01-03T00:00:00Z" },

  // Het Echte Leven in de ZOO S1
  { id: "ep-4-1", show_id: "show-4", title: "Welkom in Planckendael", description: "We ontmoeten de bewoners van de dierentuin voor het eerst.", video_url: VIDEOS[8], season: 1, episode_number: 1, duration: 2700, thumbnail: IMAGES["zoo"].thumb, created_at: "2025-01-04T00:00:00Z" },
  { id: "ep-4-2", show_id: "show-4", title: "De Olifantenfamilie", description: "Een kijkje in het leven van de olifanten van Planckendael.", video_url: VIDEOS[9], season: 1, episode_number: 2, duration: 2700, thumbnail: IMAGES["zoo"].thumb, created_at: "2025-01-04T00:00:00Z" },

  // Moordzaken S1
  { id: "ep-5-1", show_id: "show-5", title: "De laatste nacht", description: "Reconstructie van een moordzaak waarbij liefde omslaat in haat.", video_url: VIDEOS[0], season: 1, episode_number: 1, duration: 3600, thumbnail: IMAGES["moordzaken"].thumb, created_at: "2025-01-05T00:00:00Z" },
  { id: "ep-5-2", show_id: "show-5", title: "Jaloezie als motief", description: "Wanneer obsessie dodelijk wordt.", video_url: VIDEOS[1], season: 1, episode_number: 2, duration: 3600, thumbnail: IMAGES["moordzaken"].thumb, created_at: "2025-01-05T00:00:00Z" },

  // De Box S1
  { id: "ep-6-1", show_id: "show-6", title: "Dag 1: De regels zijn onbekend", description: "Tien Vlamingen openen hun eerste box.", video_url: VIDEOS[2], season: 1, episode_number: 1, duration: 3600, thumbnail: IMAGES["de-box"].thumb, created_at: "2025-01-06T00:00:00Z" },
  { id: "ep-6-2", show_id: "show-6", title: "Dag 2: Vertrouwen of bedriegen", description: "Allianties worden gesmeed, maar wie is te vertrouwen?", video_url: VIDEOS[3], season: 1, episode_number: 2, duration: 3600, thumbnail: IMAGES["de-box"].thumb, created_at: "2025-01-06T00:00:00Z" },

  // Datenight S1
  { id: "ep-7-1", show_id: "show-7", title: "Eerste liefde", description: "Tess en haar gast duiken in hun pril verleden.", video_url: VIDEOS[4], season: 1, episode_number: 1, duration: 2700, thumbnail: IMAGES["datenight"].thumb, created_at: "2025-01-07T00:00:00Z" },
  { id: "ep-7-2", show_id: "show-7", title: "Liefdesverdriet", description: "Hoe groot kan een gebroken hart zijn?", video_url: VIDEOS[5], season: 1, episode_number: 2, duration: 2700, thumbnail: IMAGES["datenight"].thumb, created_at: "2025-01-07T00:00:00Z" },

  // De Mutti's S1
  { id: "ep-8-1", show_id: "show-8", title: "Welkom in de praatgroep", description: "Zeven mama's ontmoeten elkaar voor het eerst.", video_url: VIDEOS[6], season: 1, episode_number: 1, duration: 2700, thumbnail: IMAGES["de-muttis"].thumb, created_at: "2025-01-08T00:00:00Z" },
  { id: "ep-8-2", show_id: "show-8", title: "Slaaptekort en chaos", description: "De mama's delen hun grootste frustraties.", video_url: VIDEOS[7], season: 1, episode_number: 2, duration: 2700, thumbnail: IMAGES["de-muttis"].thumb, created_at: "2025-01-08T00:00:00Z" },

  // Gooische Vrouwen S1
  { id: "ep-9-1", show_id: "show-9", title: "Rijkdom heeft een prijs", description: "We ontmoeten de vriendinnen van het Gooi.", video_url: VIDEOS[8], season: 1, episode_number: 1, duration: 2700, thumbnail: IMAGES["gooische-vrouwen"].thumb, created_at: "2025-01-09T00:00:00Z" },
  { id: "ep-9-2", show_id: "show-9", title: "Scheuren in de façade", description: "De eerste spanningen duiken op tussen de vriendinnen.", video_url: VIDEOS[9], season: 1, episode_number: 2, duration: 2700, thumbnail: IMAGES["gooische-vrouwen"].thumb, created_at: "2025-01-09T00:00:00Z" },

  // Familie S1
  { id: "ep-10-1", show_id: "show-10", title: "Aflevering 1", description: "De Van den Bossche-familie start een nieuw hoofdstuk.", video_url: VIDEOS[0], season: 1, episode_number: 1, duration: 1800, thumbnail: IMAGES["familie"].thumb, created_at: "2025-01-10T00:00:00Z" },
  { id: "ep-10-2", show_id: "show-10", title: "Aflevering 2", description: "Spanningen lopen hoog op in de familie.", video_url: VIDEOS[1], season: 1, episode_number: 2, duration: 1800, thumbnail: IMAGES["familie"].thumb, created_at: "2025-01-10T00:00:00Z" },

  // Alter Ego S1
  { id: "ep-11-1", show_id: "show-11", title: "Het mysterie begint", description: "Gilles ontmoet een vreemde figuur uit zijn verleden.", video_url: VIDEOS[2], season: 1, episode_number: 1, duration: 3000, thumbnail: IMAGES["alter-ego"].thumb, created_at: "2025-01-11T00:00:00Z" },
  { id: "ep-11-2", show_id: "show-11", title: "Salvator", description: "De private bank Salvator verbergt meer dan verwacht.", video_url: VIDEOS[3], season: 1, episode_number: 2, duration: 3000, thumbnail: IMAGES["alter-ego"].thumb, created_at: "2025-01-11T00:00:00Z" },

  // Verliefd verloofd getrouwd S1
  { id: "ep-12-1", show_id: "show-12", title: "Het aanzoek", description: "Drie koppels zeggen ja en beginnen aan hun 24-uur avontuur.", video_url: VIDEOS[4], season: 1, episode_number: 1, duration: 3600, thumbnail: IMAGES["verliefd"].thumb, created_at: "2025-01-12T00:00:00Z" },
  { id: "ep-12-2", show_id: "show-12", title: "Naar het altaar", description: "De grote dag breekt aan in minder dan 24 uur.", video_url: VIDEOS[5], season: 1, episode_number: 2, duration: 3600, thumbnail: IMAGES["verliefd"].thumb, created_at: "2025-01-12T00:00:00Z" },

  // Tracker S1
  { id: "ep-13-1", show_id: "show-13", title: "De eerste vermiste", description: "Colter Shaw neemt zijn eerste zaak aan.", video_url: VIDEOS[6], season: 1, episode_number: 1, duration: 3000, thumbnail: IMAGES["tracker"].thumb, created_at: "2025-01-13T00:00:00Z" },
  { id: "ep-13-2", show_id: "show-13", title: "Geen spoor", description: "De zoektocht leidt naar gevaarlijk terrein.", video_url: VIDEOS[7], season: 1, episode_number: 2, duration: 3000, thumbnail: IMAGES["tracker"].thumb, created_at: "2025-01-13T00:00:00Z" },

  // The Couple Next Door S1
  { id: "ep-14-1", show_id: "show-14", title: "De nieuwe buren", description: "Evie en haar partner leren hun buren kennen.", video_url: VIDEOS[8], season: 1, episode_number: 1, duration: 3000, thumbnail: IMAGES["couple-next-door"].thumb, created_at: "2025-01-14T00:00:00Z" },
  { id: "ep-14-2", show_id: "show-14", title: "Gevaarlijke aantrekkingskracht", description: "De spanning tussen de vier stijgt.", video_url: VIDEOS[9], season: 1, episode_number: 2, duration: 3000, thumbnail: IMAGES["couple-next-door"].thumb, created_at: "2025-01-14T00:00:00Z" },

  // Love Island UK S1
  { id: "ep-15-1", show_id: "show-15", title: "Welkom op het eiland", description: "De singles komen aan in de villa en kiezen hun eerste koppels.", video_url: VIDEOS[0], season: 1, episode_number: 1, duration: 3600, thumbnail: IMAGES["love-island"].thumb, created_at: "2025-01-15T00:00:00Z" },
  { id: "ep-15-2", show_id: "show-15", title: "De eerste koppeling", description: "Harten worden gebroken en nieuwe liefdes ontluiken.", video_url: VIDEOS[1], season: 1, episode_number: 2, duration: 3600, thumbnail: IMAGES["love-island"].thumb, created_at: "2025-01-15T00:00:00Z" },

  // Florentina S1
  { id: "ep-16-1", show_id: "show-16", title: "Gedumpt en geërfd", description: "Flo's leven wordt op zijn kop gezet op dezelfde dag.", video_url: VIDEOS[2], season: 1, episode_number: 1, duration: 2700, thumbnail: IMAGES["florentina"].thumb, created_at: "2025-01-16T00:00:00Z" },
  { id: "ep-16-2", show_id: "show-16", title: "De geheime nachtclub", description: "Flo ontdekt wat haar nonkel heeft nagelaten.", video_url: VIDEOS[3], season: 1, episode_number: 2, duration: 2700, thumbnail: IMAGES["florentina"].thumb, created_at: "2025-01-16T00:00:00Z" },

  // Huis Gemaakt S1
  { id: "ep-17-1", show_id: "show-17", title: "De renovatie begint", description: "Vier koppels starten aan hun ultieme renovatierace.", video_url: VIDEOS[4], season: 1, episode_number: 1, duration: 4500, thumbnail: IMAGES["huis-gemaakt"].thumb, created_at: "2025-01-17T00:00:00Z" },
  { id: "ep-17-2", show_id: "show-17", title: "Problemen in de muren", description: "Onverwachte tegenslagen zetten de renovaties onder druk.", video_url: VIDEOS[5], season: 1, episode_number: 2, duration: 4500, thumbnail: IMAGES["huis-gemaakt"].thumb, created_at: "2025-01-17T00:00:00Z" },

  // Films (één episode = volledige film)
  { id: "ep-18-1", show_id: "show-18", title: "Hamnet", description: "Volledige film — het verhaal achter Hamlet.", video_url: VIDEOS[6], season: 1, episode_number: 1, duration: 6600, thumbnail: IMAGES["hamnet"].thumb, created_at: "2025-01-18T00:00:00Z" },
  { id: "ep-19-1", show_id: "show-19", title: "Spider-Man", description: "Volledige film — de oorsprong van Spider-Man.", video_url: VIDEOS[7], season: 1, episode_number: 1, duration: 7380, thumbnail: IMAGES["spider-man"].thumb, created_at: "2025-01-19T00:00:00Z" },
  { id: "ep-20-1", show_id: "show-20", title: "Spider-Man 2", description: "Volledige film — Spider-Man tegenover dokter Octopus.", video_url: VIDEOS[8], season: 1, episode_number: 1, duration: 7740, thumbnail: IMAGES["spider-man-2"].thumb, created_at: "2025-01-20T00:00:00Z" },
  { id: "ep-21-1", show_id: "show-21", title: "Spider-Man 3", description: "Volledige film — de duistere kant van Peter Parker.", video_url: VIDEOS[9], season: 1, episode_number: 1, duration: 8040, thumbnail: IMAGES["spider-man-3"].thumb, created_at: "2025-01-21T00:00:00Z" },
  { id: "ep-22-1", show_id: "show-22", title: "King of Thieves", description: "Volledige film — de Hatton Garden kraak.", video_url: VIDEOS[0], season: 1, episode_number: 1, duration: 6480, thumbnail: IMAGES["king-of-thieves"].thumb, created_at: "2025-01-22T00:00:00Z" },
  { id: "ep-23-1", show_id: "show-23", title: "Swordfish", description: "Volledige film — een hacker in de val.", video_url: VIDEOS[1], season: 1, episode_number: 1, duration: 6180, thumbnail: IMAGES["swordfish"].thumb, created_at: "2025-01-23T00:00:00Z" },
  { id: "ep-24-1", show_id: "show-24", title: "Lock Out", description: "Volledige film — reddingsmissie in de ruimte.", video_url: VIDEOS[2], season: 1, episode_number: 1, duration: 5580, thumbnail: IMAGES["lock-out"].thumb, created_at: "2025-01-24T00:00:00Z" },
];
